// Constants.js
export const reducerCases = {
    SET_TOKEN: "SET_TOKEN",
    SET_USER: "SET_USER",
    SET_PLAYLISTS: "SET_PLAYLISTS",
    SET_PLAYING: "SET_PLAYING",
    SET_PLAYER_STATE: "SET_PLAYER_STATE",
    SET_PLAYLIST: "SET_PLAYLIST",
    SET_PLAYLIST_ID: "SET_PLAYLIST_ID",
    SET_DEVICE_ID: "SET_DEVICE_ID", // Added this line
    SET_SHUFFLE_STATE: "SET_SHUFFLE_STATE",
    SET_REPEAT_STATE: "SET_REPEAT_STATE",
    SET_UPDATE_PLAYLISTS: "SET_UPDATE_PLAYLISTS",
    SET_VOLUME: "SET_VOLUME",
    SET_PREVIOUS_VOLUME: "SET_PREVIOUS_VOLUME",
    SET_MUTED: "SET_MUTED",
    SET_SEARCH_TERM: "SET_SEARCH_TERM",
    SET_PROGRESS: "SET_PROGRESS", // Added this
    SET_DURATION: "SET_DURATION", // Added this
  };
  